# Generated by Django 4.2.11 on 2024-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_disease_client_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
