# Generated by Django 4.2.11 on 2024-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_client_age_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
