# Generated by Django 4.2.11 on 2024-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
